### ISSUE TITLE
Parameter Names not properly referenced.

### ISSUE THREAD

**Issue by jrDev1** [LifeandStyleMedia/UAlive#57] opened 2020-09-15 19:01 UTC
Changing a parameters name creates a new reference of that parameter instead of renaming it.

<img width="185" alt="image" src="https://user-images.githubusercontent.com/16272193/93253068-5995c800-f764-11ea-9350-6de387270407.png">

Thanks,
jrDev

**Comment by JasonJonesLASM** [comment] 2020-09-15 19:23
This one isn't a bug, but I'll leave it open as a future suggestion. This is just the behavior of units defining. You can't change the underlying key without it creating a new port for you automatically. I could get around it in theory, by assigning it as index and changing the descriptors to reference the name of the variable and change it's label to that, but since it's actually not a bug, it wouldn't be something I'll get to immediately. I'll keep it open so I can remember to do this later.

**Comment by jrDev1** [comment] 2020-09-16 14:32
Ok.

**Comment by JasonJonesLASM** [comment] 2020-09-29 13:15
There is only two ways to do this, assign ports by index, or by name. We can do it by name and this occurs, eventually we're going to run into this with reordering in the future, so neither one will work. I'll maybe revisit this behaviour, but this is the same behavior you'd get with a Graph input unit and super units so I'm going to keep it the same for now.

**Closed by JasonJonesLASM** 2020-09-29 13:15 UTC
Labels: Not A Bug
