### ISSUE TITLE
Error Generating Native Code when no variables added  

### ISSUE THREAD

**Issue by jrDev1** [LifeandStyleMedia/UAlive#39] opened 2020-09-11 00:23 UTC
ArgumentException: Path is empty
System.IO.Directory.CreateDirectory (System.String path) (at <fb001e01371b4adca20013e0ac763896>:0)
Lasm.UAlive.HUMIO_Children.Custom (Lasm.UAlive.HUMIO+Data+Save saveData, System.String filePath, System.String fileName) (at Assets/LifeandStyleMedia/UAlive/Humility/IO/HUMIO_Children.cs:42)
Lasm.UAlive.ClassExtensions.Save (System.String guid, Lasm.UAlive.CustomClass target, System.String code) (at Assets/LifeandStyleMedia/UAlive/Core/Runtime/Utilities/ClassExtensions.cs:12)
Lasm.UAlive.CustomClassGenerator.SaveCompiled () (at Assets/LifeandStyleMedia/UAlive/Core/Editor/Constructs/Generators/CustomClassGenerator.cs:35)
Lasm.UAlive.CustomTypeGenerator`2[TGenerator,TMacro].GenerateCompiledCode () (at Assets/LifeandStyleMedia/UAlive/Core/Editor/Constructs/Generators/CustomTypeGenerator.cs:23)

This happens when no variables are added it seems.

Thanks,
jrDev

**Comment by JasonJonesLASM** [comment] 2020-09-14 17:21
Duplicate of Native C# Path being empty: (https://github.com/LifeandStyleMedia/UAlive/issues/40)

**Closed by JasonJonesLASM** 2020-09-14 17:21 UTC
Labels: Bug
