### ISSUE TITLE
Reroute Unit continuity issue

### ISSUE THREAD

**Issue by thezoob** [LifeandStyleMedia/UAlive#74] opened 2020-09-25 15:52 UTC
![Reroute Unit](https://i.imgur.com/2wvChu0.gif)

Seems to only happen when it's between 2 Reroute units and when trying to replace an existing connection.

**Comment by JasonJonesLASM** [comment] 2020-09-25 15:55
Duplicate of https://github.com/LifeandStyleMedia/UAlive/issues/73

**Closed by JasonJonesLASM** 2020-09-25 15:55 UTC
